import SignIn from '@/components/Signin'
import React from 'react'

export const metadata = {
  title: "Signin | Fresh Cart",
  description: "Generated by create next app",
};


export default function SiginPage() {
  return (
   <>
   <SignIn />
   </>
  )
}
