import SignUp from '@/components/SignUp'
import React from 'react'

export const metadata = {
  title: "Signup | Fresh Cart",
  description: "Generated by create next app",
};

export default function SigupPage() {
  return (
   <>
   <SignUp />
   </>
  )
}
