import Footer from "@/components/global/Footer";
import "./globals.css";
import Header from "@/components/global/Header";



export const metadata = {
  title: "Home | Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
        <Header />
        <main className="min-h-dvh">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
